# Generated by Django 2.1.2 on 2019-01-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='learners',
            field=models.ManyToManyField(blank=True, related_name='learners', to='learners.Learner'),
        ),
    ]
