# Generated by Django 2.1.2 on 2019-01-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(blank=True, max_length=32)),
                ('patronymic', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
