# Generated by Django 2.1.2 on 2019-01-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
