# Generated by Django 2.1.2 on 2019-01-23 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_group_learners'),
        ('courses', '0005_auto_20190120_0625'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('lesson_type', models.CharField(choices=[('event', 'Event'), ('session', 'Session')], default='session', max_length=10, verbose_name='Тип занятия')),
                ('location', models.CharField(blank=True, max_length=24, verbose_name='Место занятия')),
                ('bg_color', models.CharField(blank=True, max_length=24)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.Course')),
                ('groups', models.ManyToManyField(blank=True, related_name='groups', to='groups.Group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
