# Generated by Django 2.1.2 on 2019-01-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='learners.Learner')),
            ],
        ),
    ]
